<?php

/**
 * @file
 * Contains hooks for Config Override Core Fields.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function config_override_core_fields_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  switch ($form_id) {
    case 'search_admin_settings':
      // search.module.
      // @see \Drupal\search\SearchPageListBuilder
      $form['indexing_throttle']['cron_limit']['#config']['key'] = 'search.settings:index.cron_limit';
      $form['indexing_settings']['minimum_word_size']['#config']['key'] = 'search.settings:index.minimum_word_size';
      $form['indexing_settings']['overlap_cjk']['#config']['key'] = 'search.settings:index.overlap_cjk';
      $form['logging']['logging']['#config']['key'] = 'search.settings:logging';
      break;

  }

}
