<?php

/**
 * @file
 * Contains hooks for Config Override Core Fields.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function config_override_core_fields_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  switch ($form_id) {
    case 'search_admin_settings':
      // search.module.
      // @see \Drupal\search\SearchPageListBuilder
      $form['indexing_throttle']['cron_limit']['#config']['key'] = 'search.settings:index.cron_limit';
      $form['indexing_settings']['minimum_word_size']['#config']['key'] = 'search.settings:index.minimum_word_size';
      $form['indexing_settings']['overlap_cjk']['#config']['key'] = 'search.settings:index.overlap_cjk';
      $form['logging']['logging']['#config']['key'] = 'search.settings:logging';
      break;

    case 'system_cron_settings':
      // system.module.
      // @see \Drupal\system\Form\CronForm
      $form['cron']['logging']['#config']['key'] = 'system.cron:logging';

      // automated_cron.module.
      // @see \automated_cron_form_system_cron_settings_alter()
      if (isset($form['cron']['interval'])) {
        $form['cron']['interval']['#config']['key'] = 'automated_cron.settings:interval';
      }
      break;

    case 'system_file_system_settings':
      // system.module.
      // @see \Drupal\system\Form\FileSystemForm
      $form['file_temporary_path']['#config']['key'] = 'system.file:path.temporary';
      $form['file_default_scheme']['#config']['key'] = 'system.file:default_scheme';
      $form['temporary_maximum_age']['#config']['key'] = 'system.file:temporary_maximum_age';
      break;

    case 'system_logging_settings':
      // system.module.
      // @see \Drupal\system\Form\LoggingForm
      $form['error_level']['#config']['key'] = 'system.logging:error_level';

      // dblog.module.
      // @see \dblog_form_system_logging_settings_alter()
      if (isset($form['dblog_row_limit'])) {
        $form['dblog_row_limit']['#config']['key'] = 'dblog.settings:row_limit';
      }
      break;

  }

}
